# Generated by Django 4.0.3 on 2022-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0004_newspost_image_alter_newspost_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.TextField(blank=True, default='', max_length=900),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(blank=True, default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
