# Generated by Django 4.0.3 on 2022-05-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0010_coverbanner_tag_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverbanner',
            name='description',
            field=models.CharField(blank=True, default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='coverbanner',
            name='tag_line',
            field=models.CharField(blank=True, default='', max_length=900),
        ),
    ]
