# Generated by Django 4.0.3 on 2022-05-09 19:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0011_alter_coverbanner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
