# Generated by Django 4.0.3 on 2022-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0015_alter_coverbanner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverbanner',
            name='description',
            field=models.CharField(blank=True, default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='coverbanner',
            name='tag_line',
            field=models.CharField(blank=True, default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
