# Generated by Django 4.0.3 on 2022-05-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0017_alter_sticky_date_alter_sticky_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverbanner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
