# Generated by Django 4.0.3 on 2022-05-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0018_coverbanner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
