# Generated by Django 4.0.3 on 2022-04-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0007_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='manage',
            field=models.CharField(blank=True, choices=[('s', 'Show'), ('', 'Hide'), ('d', 'DELETE')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sticky',
            name='manage',
            field=models.CharField(blank=True, choices=[('s', 'Show'), ('', 'Hide'), ('d', 'DELETE')], default='', max_length=10),
        ),
    ]
