# Generated by Django 4.0.3 on 2022-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0008_image_manage_sticky_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
