# Generated by Django 4.0.3 on 2022-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0009_coverbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverbanner',
            name='tag_line',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
