# Generated by Django 4.0.3 on 2022-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondSight', '0016_alter_coverbanner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticky',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sticky',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
